### ISSUE TITLE
How can I remove one of the actions in toolbar

### ISSUE THREAD

**Issue by yasir-netlinks** [stulip/react-native-pell-rich-editor#15]
Hi there, I want to remove the `insert image` action in toolbar, can I do that??

**Comment by whitesnow9291** [comment]
```
import { actions  as RichEditorActions} from 'react-native-pell-rich-editor';

 <RichToolbar
   {...}
   actions = {[RichEditorActions. setBold, ...]}
    /> 
```                  
This will add just Bold action, you can add more you want.

**Comment by sourabhbagrecha** [comment]
A slight change in the current version (v1.0.6):
import { ~actions~ **DefaultActions** as RichEditorActions} from 'react-native-pell-rich-editor';
