### ISSUE TITLE
How to get the latest HTML in RN

### ISSUE THREAD

**Issue by liyukeGit** [stulip/react-native-pell-rich-editor#2]
How to get the latest HTML in RN
在RN中如何获取最新的html

How do I add pictures from RN?
如何从RN这里添加图片？

**Comment by astulip** [comment]
`<RichEditor  ref={ref => store.richText = ref} />`
`// Get HTML`
`let html = await that.richText.getContentHtml();`

`Add Image Base64`
`this.richText.insertImage(`data:${image.mime};base64,${image.data}`);`

**Comment by ProFullStackDev** [comment]
can you give an example on how to use getContentHtml()  on current value change
