### ISSUE TITLE
Programmatic focus on the text area not opening the keyboard on both ios and android

### ISSUE THREAD

**Issue by deen804** [stulip/react-native-pell-rich-editor#20]
Am on react native 0.57 and Programmatic focus on the text area not opening the keyboard on both ios(13.0.1) and android (latest).

**Comment by khurana3192** [comment]
+1

**Comment by DAmisonSSG** [comment]
+1

**Comment by AnuragTiwari1** [comment]
+1

**Comment by AnuragTiwari1** [comment]
+1

**Comment by harshaanNihal** [comment]
+1

**Comment by wxik** [comment]
@deen804 Is it the problem mentioned here [https://github.com/react-native-community/react-native-webview/issues/1172#issue-556270246](https://github.com/react-native-community/react-native-webview/issues/1172#issue-556270246)

**Comment by wxik** [comment]
#https://github.com/react-native-community/react-native-webview/issues/1172#issuecomment-655434500
