### ISSUE TITLE
setContentFocusHandler - more information on this?

### ISSUE THREAD

**Issue by khurana3192** [stulip/react-native-pell-rich-editor#24]
Hey,

I am trying to catch an event which gets triggered as soon as this editor is focussed.

Can you please help me achieve this?

**Comment by khurana3192** [comment]
Basically, if there are more inputs on the same page, the toolbar appears for every other input which is not the desired behaviour. The toolbar should only appear if the richeditor gains focus.

**Comment by khurana3192** [comment]
I got this to work finally. If anyone is looking forward to this implementation, I can explain.

**Comment by lakshanmamalgaha** [comment]
can you explain how you did this

**Comment by ppv94** [comment]
How to autofocus on editor assoon as editor is open

**Comment by khurana3192** [comment]
I went into source code and found that in the Javascript counterpart you
have to enable auto focus.


Regards,

*Prateek Khurana*
Software Engineer / Freelance Developer
+919958255298, +917007813799 <+919958255298,+917007813799> |   Skype:
prateek.khurana31 <https://webapp.wisestamp.com/#>
<http://www.facebook.com/prateek.khurana31>
<http://in.linkedin.com/in/prateekkhurana31>
