### ISSUE TITLE
how to get content that was typed inside the editor?

### ISSUE THREAD

**Issue by ambessh** [stulip/react-native-pell-rich-editor#27]

**Comment by ppv94** [comment]
<RichEditor
         ref={rf => that.richText = rf}
          initialContentHTML={initHTML}
          style={styles.rich}
    />
when you click save buttom keep below code in save function you will get output in HTML formate.
`save(){
let html = await this.richText.getContentHtml();
        alert( html);
}`

**Comment by ambessh** [comment]
Thanks .i want another favour . I want to show whats typed inside the editor somewhere else but getContentHtml provides with html tags . how to get content without tags . Is there any way ?? thanks again

**Comment by ambessh** [comment]
i got the solution 
function striphtml(str)
{
   if ((str===null) || (str===''))
       return false;
  else
   str = str.toString();
  return str.replace(/<[^>]*>/g, '');
}
console.log(striphtml(your html));

**Comment by delavago** [comment]
> <RichEditor
> ref={rf => that.richText = rf}
> initialContentHTML={initHTML}
> style={styles.rich}
> />
> when you click save buttom keep below code in save function you will get output in HTML formate.
> `save(){ let html = await this.richText.getContentHtml(); alert( html); }`

does this actually work cause i can't get it to work

**Comment by wxik** [comment]
`onChange` props has been supported in `1.0.8`
