### ISSUE TITLE
How to auto focus as soon as editor is open in react-native

### ISSUE THREAD

**Issue by ppv94** [stulip/react-native-pell-rich-editor#28]
I am using **react-native-pell-rich-editor** in my react-native application, How can we autofocus the cursor as soon as the editor is open in the react-native application.

**Comment by krisnailafat** [comment]
this library might be help
https://github.com/TryImpossible/react-native-enhance-webview

it has auto focus
the first issue right here 
https://github.com/facebook/react-native/issues/18965

and i just dont know how to integrate

**Comment by sureshbakshi** [comment]
focusContentEditor() is not working in Android.

**Comment by wxik** [comment]
@sureshbakshi 
`1.0.8` fixed focusContentEditor
`1.0.9-beta.0` fixed android focus keyboard open

**Comment by wxik** [comment]
`1.1.0` new props initialFocus to the editor initial request focus
