### ISSUE TITLE
Provide better example with real world usage 

### ISSUE THREAD

**Issue by AfanasievN** [stulip/react-native-pell-rich-editor#3]
Hello, can you please provide a good example to use.
Docs provided is not enough for the moment to use this lib with the full power of the creator.

Thanks for your impact to react-native!

**Comment by astulip** [comment]
Ok, thank you for your suggestion.
I will take the time to submit an example.

**Comment by astulip** [comment]
submit  example 

https://github.com/stulip/react-native-pell-rich-editor/tree/master/examples
