### ISSUE TITLE
[Request] Please support chaning 'Javascript' title in Link

### ISSUE THREAD

**Issue by JaeWangL** [stulip/react-native-pell-rich-editor#34]
Plesae support edit text 'javascript' title in `link` input modal

**Comment by QuinnRhys89** [comment]
Any word on when this can be fixed?

**Comment by gn01121991** [comment]
any update on this ?

**Comment by jeevankumarkanuganti** [comment]
any update on this ?

**Comment by wxik** [comment]
Sorry, take the time to implement this feature recently

**Comment by Emberice86** [comment]
Your new realization is not working. I use the latest v.1.0.7 and onInsertLink() is not triggering. It continues to work in the way as it worked before - showing modal for link insertion. It looks like for some reason this part of code left not updated          
   
case actions.insertLink:
                if (this.props.onInsertLink) {
                    this.props.onInsertLink();
                    break;
                }

**Comment by wxik** [comment]
`onInsertLink` already exists in the `1.0.8` release, see the example project for usage

**Comment by jeevankumarkanuganti** [comment]
any update on this ?

**Comment by stulip** [comment]
@jeevankumarkanuganti The current version already supports this feature

**Comment by jeevankumarkanuganti** [comment]
@stulip,

How to change the title?


Thanks in advance

**Comment by stulip** [comment]
@jeevankumarkanuganti Sorry, I got it wrong. Currently does not support modifying the existing link title

**Comment by crosswin-ecgroup** [comment]
Try this, Hope it will works,


` const insertLink = (): void => {
    // you can easily add videos from your gallery
    Alert.prompt('Insert Link', 'Enter the Link', [
      {text: LABLE.COMMON.CANCEL, style: 'cancel', onPress: () => {}},
      {
        text: LABLE.COMMON.INSERT,
        onPress: (text: any) => {
          RichText.current?.insertLink(null, text);
        },
      },
    ]);
  };`
  
  
  `<RichToolbar
                  style={{
                    backgroundColor: COLORS.WHITE,
                  }}
                  onInsertLink={insertLink}/>`

**Comment by BadhanGanesh-HappyFox** [comment]
@crosswin-ecgroup 

`Alert.prompt` works only on iOS. It is not supported in Android.

**Comment by MeenachiSundaram18** [comment]
I fixed it by developing custom dialog to handle the insert link functionality. Please check.
 https://github.com/wxik/react-native-rich-editor/issues/204#issuecomment-1714386729
