### ISSUE TITLE
Would you give an example on how to use getContentHtml()

### ISSUE THREAD

**Issue by ProFullStackDev** [stulip/react-native-pell-rich-editor#4]
using ref i called getContentHtml() but i got "Possible Unhandled Promise Rejection (id: 0):
"timeout""

**Comment by astulip** [comment]
@ProFullStackDev Do you use the following methods to get

 using ref
`async saveContent() {
    let html = await this.richText.getContentHtml();
    console.log(html);
}`
	
`saveContent2 (){
	this.richText.getContentHtml().then(html => {
		console.log(html);
	}).catch(error => {
		console.log(error);
	});
}
`

**Comment by ProFullStackDev** [comment]
check out my example code below, still getting "timeout" in response.
Can you try it and help me out if I am doing it the wrong way. 
 


import React, {Component} from 'react';
import {View,Button} from 'react-native';
import {RichEditor,RichToolbar} from 'react-native-pell-rich-editor';
export default class App extends Component {
  constructor(props){
    super(props);
    this.state={
      value: '<br/><br/><img src="https://images.unsplash.com/photo-1500382017468-9049fed747ef" height="202" width="402">',
      savedValue: ''
    }
    
  }
  
  async getHtml(){
  let html = await this.richText.getContentHtml();
  this.setState({savedValue:html})
  console.log(html);
 }
  
  render() {
    
    return (
      <View>
    <RichEditor
   ref={(r) => {this.richText = r;}}
   editorInitializedCallback={() => this.richText.setContentHTML(this.state.value)}
    />
   <RichToolbar getEditor={() => this.richText}/>
   <Button title="Save" onPress={() => this.getHtml()}/>

      </View>
    );
  }
}

**Comment by astulip** [comment]
@ProFullStackDev I have modified your demo, please try if it is feasible.

import React, {Component} from 'react';
import {View,Button} from 'react-native';
import {RichEditor,RichToolbar} from 'react-native-pell-rich-editor';
export default class App extends Component {
	constructor(props){
		super(props);
		this.initHTML = '<br/><br/><img src="https://images.unsplash.com/photo-1500382017468-9049fed747ef" height="202" width="402">';
		
	}
	
	async getHtml(){
		// Get the data here and call the interface to save the data
	let html = await this.richText.getContentHtml();
	console.log(html);
 }
	
	render() {
		
		return (
			<View>
		<RichEditor
	 ref={rf => this.richText = rf}
	initialContentHTML={this.initHTML}
		/>
	 <RichToolbar getEditor={() => this.richText}/>
	 <Button title="Save" onPress={() => this.getHtml()}/>

			</View>
		);
	}
}

**Comment by ProFullStackDev** [comment]
still getting "Possible Unhandled Promise Rejection (id: 0):
"timeout" " on console
is it working for you?

**Comment by astulip** [comment]
@ProFullStackDev 
I have no test here without problems.
In addition, the picture you provided is too big for 3M.
I will submit a code containing example later.

react-native info
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
      Memory: 2.24 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.3.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by astulip** [comment]
@ProFullStackDev 
Please refer to example
https://github.com/stulip/react-native-pell-rich-editor/tree/master/examples

**Comment by ProFullStackDev** [comment]
Encountered same issue, is it coz I am using expo?

**Comment by JaeWangL** [comment]
why this issue closed?? I have same error, too
And I don't use expo

**Comment by JaeWangL** [comment]
> why this issue closed?? I have same error, too
> And I don't use expo

I found solutions.
We have to use this method with `toString()`. like

```
const content = await editorRef.current.getContentHtml();
const trueContent = content.toString();
```

Good luck! Everyone!

**Comment by kuldeepworkid** [comment]
> @ProFullStackDev Do you use the following methods to get
> 
> using ref
> `async saveContent() { let html = await this.richText.getContentHtml(); console.log(html); }`
> 
> `saveContent2 (){ this.richText.getContentHtml().then(html => { console.log(html); }).catch(error => { console.log(error); }); } `

This is not working, im using the below code and its showing TypeError:this.richText.getContentHtml is not a function.
Below is my code:
  save() {
    this.richText
      .getContentHtml()
      .then(html => {
        console.log('HTML==>', html);
      })
      .catch(error => {
        console.log(error);
      });
  }

**Comment by bittu1028** [comment]
@ProFullStackDev  any luck with this problem ?
