### ISSUE TITLE
TypeError: Cannot read property 'getContentHtml' of null

### ISSUE THREAD

**Issue by whitmanlui** [stulip/react-native-pell-rich-editor#44]
I don't know why I can't use getContentHtml, please help

TypeError: Cannot read property 'getContentHtml' of null

**Comment by astulip** [comment]
See examples project example.js save method
`save = async () => {

        // Get the data here and call the interface to save the data
        let html = await this.richText.getContentHtml();
        // console.log(html);
        alert( html);
    };`

**Comment by whitmanlui** [comment]
> See examples project example.js save method
> `save = async () => {
> 
> ```
>     // Get the data here and call the interface to save the data
>     let html = await this.richText.getContentHtml();
>     // console.log(html);
>     alert( html);
> };`
> ```

I just follow it but still got the error

**Comment by astulip** [comment]
You need to bind ref to RichEditor

`
<RichEditor
           ref={rf => .richText = rf}
          initialContentHTML={initHTML}
           style={styles.rich} />`
