### ISSUE TITLE
selectedButtonStyle not working

### ISSUE THREAD

**Issue by quanghungit** [stulip/react-native-pell-rich-editor#45]
selectedButtonStyle  and selectedIconTint not working. Can someone help me !!!

**Comment by astulip** [comment]
Thanks for submitting, I have found this bug and are fixing it.

**Comment by quanghungit** [comment]
when will there be released in the new 2.0 version?

**Comment by astulip** [comment]
It has been fixed
https://github.com/stulip/react-native-pell-rich-editor/releases/tag/v1.0.6

**Comment by quanghungit** [comment]
thanks u so much!!
