### ISSUE TITLE
Is there a way to change the webview's backgroundColor?

### ISSUE THREAD

**Issue by salatielq** [stulip/react-native-pell-rich-editor#48]
First congratulations on the lib. It was very simple to install and worked seamlessly :)

I'm developing a dark-themed app and now I have only the rich editor with a white background.

**Comment by SonPham1602** [comment]
Haha I also stuck with this, read him code and fix it

**Comment by SonPham1602** [comment]
I just read the code. and i find out this code make error.
![image](https://user-images.githubusercontent.com/43876888/80276371-7e849280-8712-11ea-8611-0e14f757efc6.png)
remove it then u will fix your code

**Comment by salatielq** [comment]
Oh! nice! Thank you!

**Comment by ajimenezdev** [comment]
@SonPham1602 have you just removed color style, or change to your desired one?

If I remove the tag the editor is still white, to make it dark mode I need to change it, and my app allows to switch theme, so I'll have to make that configurable.

have any of you already found a solution for it?

**Comment by wxik** [comment]
@ajimenezdev v1.0.7 Published 
[examples/src/example.js](url)

RichEditor new props **editorStyle**
`
**backgroundColor**?: string

**color**?: string

**placeholderColor**?: string
`

Full support for React Native Appearance dynamic settings
