### ISSUE TITLE
keyboard.dismiss() not work

### ISSUE THREAD

**Issue by sunkaigoon** [stulip/react-native-pell-rich-editor#5]
当编辑器获取焦点弹出键盘，调用keyboard.dismiss()不能收起键盘

**Comment by shayanaithal** [comment]
hey, use richTextReference.blurContentEditor() instead of keyboard.dismiss()

**Comment by astulip** [comment]
The principle of keyboard.dismiss() is only for RN, and it is not processed for WebView.
You can use the way @shayanaithal says

**Comment by JP6720** [comment]
You are right @shayanaithal . but where to set this . because there is no on submit method.
so i dont know how to hide keyboard on submit or enter button of keyboard s clicked.
