### ISSUE TITLE
Fixed Width?

### ISSUE THREAD

**Issue by ardipr193** [stulip/react-native-pell-rich-editor#54]
I have an html content with 700px width.

This is my content on react-native-webview:
![detail](https://user-images.githubusercontent.com/17697377/82290862-0daf5e00-99d2-11ea-9ceb-470b70178143.JPG)
All looks good, I can zoom in or zoom out and also I can scroll it vertically and horizontally.

But when I implement react-native-pell-rich-editor to edit the content, the width fixed to the device screen width:
![edit](https://user-images.githubusercontent.com/17697377/82290934-36cfee80-99d2-11ea-8165-1277bd2501e0.JPG)

Need solution for this.
Thank you in advance.

**Comment by baesumin** [comment]
fix it?
