### ISSUE TITLE
How to get content we typed dynamically to the editor ?

### ISSUE THREAD

**Issue by swatibohra9** [stulip/react-native-pell-rich-editor#57]

**Comment by wxik** [comment]
There are some technical problems, which can only be obtained asynchronously at present, onChange is not supported

`
 async save() {

        // Get the data here and call the interface to save the data

        let html = await this.richText.current?.getContentHtml();

        // console.log(html);

        alert(html);
    }`

**Comment by wxik** [comment]
`onChange ` props has been supported in `1.0.8`
