### ISSUE TITLE
Insert Text

### ISSUE THREAD

**Issue by ajimenezdev** [stulip/react-native-pell-rich-editor#58]
Hi, I'm looking at how to add text to the current position on the editor.

I'm working on a screen that allow the user to insert emoji/predefined text while writing.

I cannot find how to do it on the code and I'm happy to work on it and provide a PR once done.

Just checking if it is already done or working on it currently.

**Comment by ajimenezdev** [comment]
Created a PR with a solution for this issue: https://github.com/stulip/react-native-pell-rich-editor/pull/60

**Comment by wxik** [comment]
#60
