### ISSUE TITLE
Back Button close my app

### ISSUE THREAD

**Issue by superfilip123** [stulip/react-native-pell-rich-editor#7]
I dont know why, but I have some screens, and on the one of them i have your pell rich editor, and when i go to screen in witch i have this editor and go out is okey, but when i go to this screen and text something in your editor and then click backbutton my app show black screen and close. I suppose this is a webview problem, but I'm not sure. In console logs i have nothing and i not get warnings, just nothing that could guide me why this is happening.

**Comment by superfilip123** [comment]
okay i was able to solve this problem.
This help me: [https://stackoverflow.com/questions/51712310/react-native-webview-navigation-issue](https://stackoverflow.com/questions/51712310/react-native-webview-navigation-issue)
I add this to my code:

```
constructor (props) {
      super (props)
      this.state = {
        canGoBack: false
      }
    }
    
    componentDidMount () {
      BackHandler.addEventListener ('hardwareBackPress', this.handleBackPress);
    }
    
    componentWillUnmount () {
      BackHandler.removeEventListener ('hardwareBackPress', this.handleBackPress);
    }
    
    handleBackPress = () => {
      if (this.state.canGoBack) {
        this.richText.blurContentEditor (); // this is the most important element
        this.props.navigation.navigate ( 'TopicsScreen'); // its my last screen
      } Else {
        this.richText.blurContentEditor (); // this is the most important element
        this.props.navigation.navigate ( 'TopicsScreen'); // its my last screen
      }
      return true;
    }

```

And now after clicking the back button my application goes to the TopicsScreen screen without error

**Comment by astulip** [comment]
I am very happy that you can find a solution yourself.
