### ISSUE TITLE
Can't add more actions

### ISSUE THREAD

**Issue by nlshuynguyen** [stulip/react-native-pell-rich-editor#9]
How can I add more actions. I go into library and add action "heading1" like code below. But when I press it in RichToolbar, it not working.

```
const defaultActions = [
  actions.insertImage,
  actions.setBold,
  actions.setItalic,
  actions.insertBulletsList,
  actions.insertOrderedList,
  actions.insertLink,
  actions.heading1
];

function getDefaultIcon() {
  const texts = {};
  texts[actions.insertImage] = require('../img/icon_format_media.png');
  texts[actions.setBold] = require('../img/icon_format_bold.png');
  texts[actions.setItalic] = require('../img/icon_format_italic.png');
  texts[actions.insertBulletsList] = require('../img/icon_format_ul.png');
  texts[actions.insertOrderedList] = require('../img/icon_format_ol.png');
  texts[actions.insertLink] = require('../img/icon_format_link.png');
  texts[actions.heading1] = require('../img/close.png');
  return texts;
}
```

**Comment by astulip** [comment]
The development of the extended editor function has not been processed, and will be added later.

**Comment by ro1414** [comment]
Any update on when the extended editor function is going to be implemented?

**Comment by astulip** [comment]
@ro1414 It will be refactored in the near future and will be released in the new 2.0 version

**Comment by ajimenezdev** [comment]
I'm interested as well in this functionality

**Comment by wxik** [comment]
**`1.1.0`**
 [examples/src/example.js](url)

    const phizIcon = require('./assets/phiz.png');
    const htmlIcon = require('./assets/h5.png');
    const videoIcon = require('./assets/video.png');

    <RichToolbar
        style={[styles.richBar, themeBg]}
        editor={that.richText}
         iconTint={color}
         selectedIconTint={'#2095F2'}
         selectedButtonStyle={{backgroundColor: 'transparent'}}
         onPressAddImage={that.onPressAddImage}
         onInsertLink={that.onInsertLink}
         iconSize={40}
         actions={['insertVideo', ...defaultActions, 'insertEmoji', 'insertHTML']}
         iconMap={{
             insertEmoji: phizIcon,
             // insertHTML: <Text style={styles.tib}>HTML</Text>,
             insertHTML: htmlIcon,
             insertVideo: videoIcon,
         }}
         insertEmoji={that.handleEmoji}
         insertHTML={that.insertHTML}
         insertVideo={that.insertVideo}/>
